spring:
  redis:
    database: 10
    host: 139.9.208.251
    port: 6973
    password: Haichuang6666redis
  application:
    name: springboot-init
  # 默认 dev 环境
#  profiles:
#    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume_db
    username: root
    password: root123123
#    url: jdbc:mysql://139.9.208.251:3366/resume_db_test
#    username: root
#    password: Haichuang6666mysql
server:
  address: 0.0.0.0
  port: 8808
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

app:
  data:
    bucketName: zhuyifan
    endPoint: https://obs.cn-south-1.myhuaweicloud.com
    ak: LCXYX7LWVRLANEQ8NSB6
    sk: y2FktAfEm23kXfVtK810rWKRap5JEkZqXLVTr5Jl